services:
  - type: web
    name: betterbox-image-api
    env: node
    buildCommand: npm install
    startCommand: node api.js
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: http
        source: /
        targetPort: 3000